# Generated by Django 3.1.7 on 2021-05-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyInformation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
