# Generated by Django 3.1.7 on 2021-04-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitData', '0004_auto_20210411_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_paid',
            field=models.BooleanField(default=1),
        ),
    ]
