# Generated by Django 3.1.7 on 2021-04-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitData', '0006_auto_20210411_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='payment_method',
            field=models.CharField(default='', max_length=50),
        ),
    ]
