# Generated by Django 3.1.7 on 2021-04-28 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitData', '0008_auto_20210427_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_entered',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='post',
            name='statement_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
