# Generated by Django 3.1.7 on 2021-05-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitData', '0009_auto_20210427_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adjustment',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='credit',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='interest_charges',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='late_fees',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='payments',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='previous_balance',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
