# Generated by Django 3.1.7 on 2021-05-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitData', '0010_auto_20210504_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_paid',
            field=models.BooleanField(default=0, help_text='Everything below is optional. Recommended if using a credit card.'),
        ),
    ]
