# Generated by Django 3.1.7 on 2021-05-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitData', '0011_auto_20210504_1837'),
        ('SubmitData', '0011_auto_20210504_1751'),
    ]

    operations = [
    ]
