# Generated by Django 3.1.7 on 2021-05-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitData', '0012_auto_20210504_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='previous_balance',
            field=models.IntegerField(blank=True, default='0', help_text='HELLO!'),
        ),
    ]
