# Generated by Django 3.1.7 on 2021-05-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitData', '0013_auto_20210504_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.CharField(default='', help_text='Optional', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='previous_balance',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
