# Generated by Django 3.1.7 on 2021-05-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitData', '0014_auto_20210505_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='minimum_payment',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
