# Generated by Django 3.1.7 on 2021-05-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitData', '0014_auto_20210504_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test',
        ),
        migrations.AlterField(
            model_name='post',
            name='previous_balance',
            field=models.IntegerField(blank=True, default='0', help_text='Optional'),
        ),
    ]
