# Generated by Django 3.1.7 on 2021-05-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitData', '0016_auto_20210504_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_paid',
            field=models.BooleanField(default=0, help_text='EVERYTHING IS Optional'),
        ),
    ]
